apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: grade-submission
spec:
  replicas: 2
  selector:
    matchLabels:
      com.example.learning/instance: grade-submission-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1 # this is to ensure that we do not have more that 3 replicas at a time
  template:
    metadata:
      labels:
        com.example.learning/name: grade-submission
        com.example.learning/component: backend
        com.example.learning/instance: grade-submission-api
    spec:
        containers:
        - name: grade-submission-api
          image: rslim087/kubernetes-course-grade-submission-api:stateful
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 3000
